// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8arydDs7_Ezyle0f_SwXjE7N1Unykgfs',
    appId: '1:62727313:web:652b88b68b5675020ccb30',
    messagingSenderId: '62727313',
    projectId: 'tpmod11-1302210036',
    authDomain: 'tpmod11-1302210036.firebaseapp.com',
    storageBucket: 'tpmod11-1302210036.appspot.com',
    measurementId: 'G-Q13PG9KSH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVpJVILdhA-9GEXxYiUYzQF1bIYGsFP0g',
    appId: '1:62727313:android:ec945645c08e6b510ccb30',
    messagingSenderId: '62727313',
    projectId: 'tpmod11-1302210036',
    storageBucket: 'tpmod11-1302210036.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWZKBKq1nssr5qM-mnhiiA1np6rMn8I9E',
    appId: '1:62727313:ios:55eefc03d99a2ac70ccb30',
    messagingSenderId: '62727313',
    projectId: 'tpmod11-1302210036',
    storageBucket: 'tpmod11-1302210036.appspot.com',
    iosBundleId: 'com.example.tpMod11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWZKBKq1nssr5qM-mnhiiA1np6rMn8I9E',
    appId: '1:62727313:ios:55eefc03d99a2ac70ccb30',
    messagingSenderId: '62727313',
    projectId: 'tpmod11-1302210036',
    storageBucket: 'tpmod11-1302210036.appspot.com',
    iosBundleId: 'com.example.tpMod11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8arydDs7_Ezyle0f_SwXjE7N1Unykgfs',
    appId: '1:62727313:web:13296275156c79560ccb30',
    messagingSenderId: '62727313',
    projectId: 'tpmod11-1302210036',
    authDomain: 'tpmod11-1302210036.firebaseapp.com',
    storageBucket: 'tpmod11-1302210036.appspot.com',
    measurementId: 'G-GCFPDRKFPE',
  );
}
